services:
- mysql
- elasticsearch

language: node_js

node_js:
- '0.10'
- '0.11'

before_script:
- mysql -e 'create database whybug;'

after_success:
- "/bin/bash bin/metrics_travis.sh"

matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.11'

env:
  global:
  - MYSQL_USER: travis
  - DEBUG: 1
  - secure: EbUMl2PXONzF+gYkCEsAnVbB1694noPE+AhCmhdVM6VC1A7nToA9mmTpJ89iVsj8vk6F6lfeqCIwfWgpqpLX/uleOfN2cRvYZUcuSppq4cPpSV2ehumOSBiKj1bWSthe9T1w7HmmlRKgd65dy+GU7CluvSzSz2nHVthGWdvEpsk=
