services:
- postgres
- elasticsearch

language: node_js

sudo: false

node_js:
- '4.1'
- '4.2'

cache:
  directories:
    - node_modules

before_script:
- mysql -e 'create database whybug;'
- cp .env.example .env
- npm run build:frontend
- npm run build:server

after_success:
- "/bin/bash bin/metrics_travis.sh"

env:
  global:
  - DEBUG=1
  - WEB_HOST=127.0.0.1
  - WEB_PORT=8000
  - WEB_URL=http://127.0.0.1:8000
  - MYSQL_USER=root
  - SESSION_PASSWORD='some-pw-for-tests'
  - GITHUB_COOKIE_PASSWORD='some-pw-for-tests'
  - GITHUB_CLIENT_ID='some-client-id'
  - GITHUB_CLIENT_SECRET='some-pw-for-tests'
  - TWITTER_COOKIE_PASSWORD='some-pw-for-tests'
  - TWITTER_CLIENT_ID='some-client-id'
  - TWITTER_CLIENT_SECRET='some-pw-for-tests'
  - GOOGLE_COOKIE_PASSWORD='some-pw-for-tests'
  - GOOGLE_CLIENT_ID='some-client-id'
  - GOOGLE_CLIENT_SECRET='some-pw-for-tests'
  - secure=EbUMl2PXONzF+gYkCEsAnVbB1694noPE+AhCmhdVM6VC1A7nToA9mmTpJ89iVsj8vk6F6lfeqCIwfWgpqpLX/uleOfN2cRvYZUcuSppq4cPpSV2ehumOSBiKj1bWSthe9T1w7HmmlRKgd65dy+GU7CluvSzSz2nHVthGWdvEpsk=

notifications:
  email: false
