web:
  scale: 1
  metadata:
    io.rancher.service.hash: ef6f20e9c2931390034d1561104d5547416b525f
  health_check:
    port: 8000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /healthcheck HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
elasticsearch:
  scale: 1
  metadata:
    io.rancher.service.hash: b2b198f43adbc6eda8701234a7f2071a5d886a8b
postgres:
  scale: 1
  metadata:
    io.rancher.service.hash: 9c95e1a420c4a1c70b8aa425cdf2da08b1aefa78
